package transcript_test

import (
	"testing"

	"github.com/deephanson94/compass/internal/transcript"
)

// Every line here is a shape taken from a real transcript, not one invented to
// suit the parser.
func TestMachineryPromptsAreNotPeopleTalking(t *testing.T) {
	tests := []struct {
		name string
		line string
		want bool
	}{
		{"the caveat before a local command", `{"type":"user","isMeta":true,"message":{"role":"user",` +
			`"content":"<local-command-caveat>Caveat: The messages below were generated by the user while ` +
			`running local commands.</local-command-caveat>"},"uuid":"u1"}`, true},
		{"stop hook feedback", `{"type":"user","isMeta":true,"message":{"role":"user",` +
			`"content":"Stop hook feedback:\n[~/.claude/stop-hook-git-check.sh]: There are untracked files."},` +
			`"uuid":"u2"}`, true},
		{"a task notification", `{"type":"user","message":{"role":"user",` +
			`"content":"<task-notification>\n<task-id>abc</task-id>\n</task-notification>"},"uuid":"u3"}`, true},
		{"a compaction summary", `{"type":"user","message":{"role":"user",` +
			`"content":"This session is being continued from a previous conversation that ran out of context."},` +
			`"uuid":"u4"}`, true},

		{"a person talking", `{"type":"user","message":{"role":"user",` +
			`"content":"how are we handling tmux grouped sessions?"},"uuid":"u5"}`, false},
		// Prefix matching, not substring: a prompt about the machinery is a
		// prompt. This is the one that would quietly hide real work.
		{"a person talking about the machinery", `{"type":"user","message":{"role":"user",` +
			`"content":"why does a <system-reminder> reach the segmenter at all?"},"uuid":"u6"}`, false},
		// isMeta belongs to user lines; an assistant turn is never a prompt in
		// the first place, and must not be mistaken for one.
		{"an assistant turn", `{"type":"assistant","message":{"role":"assistant",` +
			`"content":[{"type":"text","text":"<system-reminder> is stripped upstream."}]},"uuid":"u7"}`, false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			ev, err := transcript.ParseLine([]byte(tc.line))
			if err != nil {
				t.Fatalf("ParseLine: %v", err)
			}
			if got := ev.Machinery(); got != tc.want {
				t.Errorf("Machinery() = %v, want %v for %q", got, tc.want, ev.Text)
			}
		})
	}
}

// A slash command is a real thing a person typed. Claude Code expands it into
// three tags and the fleet used to show the middle one, so `/kickoff` reached
// the row as "<command-message>kickoff</co…".
func TestSlashCommandReadsAsTyped(t *testing.T) {
	const expanded = "<command-name>/model</command-name>\n" +
		"            <command-message>model</command-message>\n" +
		"            <command-args>claude-opus-5</command-args>"

	got, ok := transcript.SlashCommand(expanded)
	if !ok {
		t.Fatal("a slash command was not recognised as one")
	}
	if want := "/model claude-opus-5"; got != want {
		t.Errorf("SlashCommand() = %q, want %q", got, want)
	}

	// No args is the common case — `/kickoff`, `/compact`.
	bare := "<command-name>/kickoff</command-name>\n<command-message>kickoff</command-message>"
	if got, ok := transcript.SlashCommand(bare); !ok || got != "/kickoff" {
		t.Errorf("SlashCommand(bare) = %q, %v; want %q, true", got, ok, "/kickoff")
	}

	// An empty <command-args/> must not leave a trailing space.
	empty := "<command-name>/compact</command-name>\n<command-args></command-args>"
	if got, _ := transcript.SlashCommand(empty); got != "/compact" {
		t.Errorf("SlashCommand(empty args) = %q, want %q", got, "/compact")
	}

	if _, ok := transcript.SlashCommand("just a prompt about <command-name> tags"); ok {
		t.Error("ordinary prose was read as a slash command")
	}
}
