package transcript_test

import (
	"strings"
	"testing"

	"github.com/deephanson94/compass/internal/transcript"
)

// Every line here is a shape taken from a real transcript, not one invented to
// suit the parser.
func TestMachineryPromptsAreNotPeopleTalking(t *testing.T) {
	tests := []struct {
		name string
		line string
		want bool
	}{
		{"the caveat before a local command", `{"type":"user","isMeta":true,"message":{"role":"user",` +
			`"content":"<local-command-caveat>Caveat: The messages below were generated by the user while ` +
			`running local commands.</local-command-caveat>"},"uuid":"u1"}`, true},
		{"stop hook feedback", `{"type":"user","isMeta":true,"message":{"role":"user",` +
			`"content":"Stop hook feedback:\n[~/.claude/stop-hook-git-check.sh]: There are untracked files."},` +
			`"uuid":"u2"}`, true},
		{"a task notification", `{"type":"user","message":{"role":"user",` +
			`"content":"<task-notification>\n<task-id>abc</task-id>\n</task-notification>"},"uuid":"u3"}`, true},
		{"a compaction summary", `{"type":"user","message":{"role":"user",` +
			`"content":"This session is being continued from a previous conversation that ran out of context."},` +
			`"uuid":"u4"}`, true},

		{"a person talking", `{"type":"user","message":{"role":"user",` +
			`"content":"how are we handling tmux grouped sessions?"},"uuid":"u5"}`, false},
		// Prefix matching, not substring: a prompt about the machinery is a
		// prompt. This is the one that would quietly hide real work.
		{"a person talking about the machinery", `{"type":"user","message":{"role":"user",` +
			`"content":"why does a <system-reminder> reach the segmenter at all?"},"uuid":"u6"}`, false},
		// isMeta belongs to user lines; an assistant turn is never a prompt in
		// the first place, and must not be mistaken for one.
		{"an assistant turn", `{"type":"assistant","message":{"role":"assistant",` +
			`"content":[{"type":"text","text":"<system-reminder> is stripped upstream."}]},"uuid":"u7"}`, false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			ev, err := transcript.ParseLine([]byte(tc.line))
			if err != nil {
				t.Fatalf("ParseLine: %v", err)
			}
			if got := ev.Machinery(); got != tc.want {
				t.Errorf("Machinery() = %v, want %v for %q", got, tc.want, ev.Text)
			}
		})
	}
}

// A slash command is a real thing a person typed. Claude Code expands it into
// three tags and the fleet used to show the middle one, so `/kickoff` reached
// the row as "<command-message>kickoff</co…".
func TestSlashCommandReadsAsTyped(t *testing.T) {
	const expanded = "<command-name>/model</command-name>\n" +
		"            <command-message>model</command-message>\n" +
		"            <command-args>claude-opus-5</command-args>"

	got, ok := transcript.SlashCommand(expanded)
	if !ok {
		t.Fatal("a slash command was not recognised as one")
	}
	if want := "/model claude-opus-5"; got != want {
		t.Errorf("SlashCommand() = %q, want %q", got, want)
	}

	// No args is the common case — `/kickoff`, `/compact`.
	bare := "<command-name>/kickoff</command-name>\n<command-message>kickoff</command-message>"
	if got, ok := transcript.SlashCommand(bare); !ok || got != "/kickoff" {
		t.Errorf("SlashCommand(bare) = %q, %v; want %q, true", got, ok, "/kickoff")
	}

	// An empty <command-args/> must not leave a trailing space.
	empty := "<command-name>/compact</command-name>\n<command-args></command-args>"
	if got, _ := transcript.SlashCommand(empty); got != "/compact" {
		t.Errorf("SlashCommand(empty args) = %q, want %q", got, "/compact")
	}

	if _, ok := transcript.SlashCommand("just a prompt about <command-name> tags"); ok {
		t.Error("ordinary prose was read as a slash command")
	}
}

// The shape is the one a real background agent left in a transcript. The
// tool-use-id is the whole point: it is what ties the agent's last words back
// to the Agent call that started it.
func TestATaskNotificationIsReadByItsFields(t *testing.T) {
	const text = "<task-notification>\n" +
		"<task-id>a3bee81fef2254386</task-id>\n" +
		"<tool-use-id>toolu_01H6pnwSzNJaABvYPerZAnsh</tool-use-id>\n" +
		"<output-file>/tmp/x.output</output-file>\n" +
		"<status>completed</status>\n" +
		"<summary>Agent \"Implement tmuxop pane layer\" finished</summary>\n" +
		"<note>A task-notification fires each time this agent stops.</note>\n" +
		"<result>`go build ./...` is clean.\n\nMore detail below.</result>\n" +
		"</task-notification>"

	n, ok := transcript.ParseTaskNotification(text)
	if !ok {
		t.Fatal("a task-notification was not recognised as one")
	}
	if n.ToolUseID != "toolu_01H6pnwSzNJaABvYPerZAnsh" {
		t.Errorf("ToolUseID = %q", n.ToolUseID)
	}
	if n.Status != "completed" || n.TaskID != "a3bee81fef2254386" {
		t.Errorf("Status/TaskID = %q/%q", n.Status, n.TaskID)
	}
	if n.Summary != `Agent "Implement tmuxop pane layer" finished` {
		t.Errorf("Summary = %q", n.Summary)
	}
	if want := "`go build ./...` is clean.\n\nMore detail below."; n.Result != want {
		t.Errorf("Result = %q, want %q", n.Result, want)
	}

	if _, ok := transcript.ParseTaskNotification("please look at the task-notification format"); ok {
		t.Error("prose mentioning the tag was read as a notification")
	}
}

// Two more of the harness's voices, seen on a dogfooded trail quoted as if the
// person had said them. Neither carries isMeta, so the opening words are all
// there is to go on. A background agent's echo is machinery; another
// session's message is an ask of a kind — relayed, and worn as such (#97).
func TestRelayedMessagesAreNotPrompts(t *testing.T) {
	ev := transcript.Event{Type: transcript.EventUser, Text: `Background agent "You are measuring, not summarizing. Every…" finished`}
	if !ev.Machinery() || ev.Relayed() {
		t.Errorf("a background agent's echo is not machinery: Machinery() = %v, Relayed() = %v", ev.Machinery(), ev.Relayed())
	}
	relay := transcript.Event{Type: transcript.EventUser, Text: "Another Claude session sent a message:\n\nhey, the quota is back"}
	if relay.Machinery() || !relay.Relayed() {
		t.Errorf("another session's message is an ask: Machinery() = %v, Relayed() = %v", relay.Machinery(), relay.Relayed())
	}
	if got := relay.RelayBody(); got != "hey, the quota is back" {
		t.Errorf("RelayBody() = %q", got)
	}
	// And the same words later in a prompt are still a prompt.
	ev = transcript.Event{Type: transcript.EventUser, Text: "why does Another Claude session sent a message show up?"}
	if ev.Machinery() {
		t.Error("a prompt that mentions the phrase mid-sentence was called machinery")
	}
}

// The result line Claude Code writes for TaskCreate, verbatim from a
// transcript: the model sees the text, and the structured account rides
// beside it as toolUseResult. Both reach the ToolResult.
func TestAToolResultCarriesItsStructuredAccount(t *testing.T) {
	line := `{"type":"user","uuid":"u1","timestamp":"2026-09-02T00:58:00.000Z","message":{"role":"user",` +
		`"content":[{"tool_use_id":"toolu_01","type":"tool_result",` +
		`"content":"Task #1 created successfully: Build ghost waypoints"}]},` +
		`"toolUseResult":{"task":{"id":"1","subject":"Build ghost waypoints"}},"sessionId":"s"}`
	ev, err := transcript.ParseLine([]byte(line))
	if err != nil {
		t.Fatal(err)
	}
	if len(ev.ToolResults) != 1 {
		t.Fatalf("got %d results, want 1", len(ev.ToolResults))
	}
	r := ev.ToolResults[0]
	if !strings.HasPrefix(r.Text, "Task #1 created") {
		t.Errorf("Text = %q", r.Text)
	}
	if !strings.Contains(string(r.Meta), `"id":"1"`) {
		t.Errorf("Meta = %s, want the structured toolUseResult", r.Meta)
	}
}

// A teammate's message comes in an envelope: the teammate's id and the
// message are read out of it, and a plain relay is not one (#394).
func TestATeammatesMessageIsReadOutOfItsEnvelope(t *testing.T) {
	ev := transcript.Event{Type: transcript.EventUser, Text: "Another Claude session sent a message:\n\n<teammate-message teammate_id=\"panel-theorist\" color=\"purple\">\nThe plan holds; two gates are the same root cause.\nSecond line.\n</teammate-message>"}
	id, body, ok := ev.Teammate()
	if !ok || id != "panel-theorist" || body != "The plan holds; two gates are the same root cause.\nSecond line." {
		t.Errorf("Teammate() = %q, %q, %v", id, body, ok)
	}
	plain := transcript.Event{Type: transcript.EventUser, Text: "Another Claude session sent a message: the encoder is in, run the gates"}
	if _, _, ok := plain.Teammate(); ok {
		t.Errorf("a plain relay is not a teammate's")
	}
	if _, _, ok := (transcript.Event{Type: transcript.EventUser, Text: "<teammate-message teammate_id=\"x\">hi</teammate-message>"}).Teammate(); ok {
		t.Errorf("an envelope the harness did not relay is machinery, not a teammate's message")
	}
}

// A lead's teammates come back in one relayed turn: the preamble once,
// then an envelope per message, blank-line separated. Recorded from a
// lead with five teammates (t18-teammates.jsonl, its last line): five
// envelopes, two from the same teammate, four of them carrying the
// harness's idle notification for the teammate — a JSON object whose
// `result` is what it reported, with the result's closing quote escaped
// so the object does not parse — and one the teammate's own words with
// a `summary` attribute (#396).
func TestEveryTeammateEnvelopeInATurnIsRead(t *testing.T) {
	lines := fixtureLines(t, "scenarios/t18-teammates.jsonl")
	ev, err := transcript.ParseLine([]byte(lines[len(lines)-1]))
	if err != nil {
		t.Fatal(err)
	}
	ms := ev.Teammates()
	want := []transcript.TeammateMessage{
		{ID: "scenario-batch-00", Body: "Done. Processed all 21 memory entries from batch_00.txt and generated 2 scenarios for each — no entries were too abstract to extract from.\n\n**Results:** 21 entries processed, 0 skipped. Scenarios written to `/hdd4/deep/tmp/memory_retrieval_experiment/scenarios_batch_00.json`."},
		{ID: "scenario-batch-01", Body: "Done. I processed all 22 entries in batch_01 and wrote the scenarios JSON file. Each entry generated 2 scenario sentences grounded in facts from the \\\"Why:\\\" and incident sections.\n\n**Results:** 22 entries processed, 0 skipped."},
		{ID: "scenario-batch-02", Body: "Batch 02 complete. Processed **21 entries**, **0 skipped** (all were grounded enough to produce concrete scenarios)."},
		{ID: "scenario-batch-04", Body: "Batch 04 complete: 23 entries processed, 0 skipped. Scenarios written to /hdd4/deep/tmp/memory_retrieval_experiment/scenarios_batch_04.json."},
		{ID: "scenario-batch-04", Body: "Done. All 23 memory entries from batch_04.txt processed.\n\n**Results:** 23 entries processed, 0 skipped."},
	}
	if len(ms) != len(want) {
		t.Fatalf("Teammates() = %d messages, want %d:\n%+v", len(ms), len(want), ms)
	}
	for i := range want {
		if ms[i] != want[i] {
			t.Errorf("Teammates()[%d] = %+v\nwant %+v", i, ms[i], want[i])
		}
	}
	// Teammate() is the first of them.
	if id, body, ok := ev.Teammate(); !ok || id != want[0].ID || body != want[0].Body {
		t.Errorf("Teammate() = %q, %q, %v", id, body, ok)
	}
	// A prose envelope is read as written; an idle notification that does
	// parse is read by its result; one with no result is read as written.
	one := func(body string) string {
		ev := transcript.Event{Type: transcript.EventUser, Text: "Another Claude session sent a message:\n<teammate-message teammate_id=\"x\">\n" + body + "\n</teammate-message>"}
		_, b, _ := ev.Teammate()
		return b
	}
	if got := one(`{"type":"idle_notification","from":"x","idleReason":"available","result":"All done.\nSecond line."}`); got != "All done.\nSecond line." {
		t.Errorf("a well-formed idle notification reads as its result: %q", got)
	}
	if got := one(`{"type":"idle_notification","from":"x","idleReason":"available"}`); got != `{"type":"idle_notification","from":"x","idleReason":"available"}` {
		t.Errorf("a notification without a result reads as written: %q", got)
	}
	if got := one("{not json, just a brace to open with}"); got != "{not json, just a brace to open with}" {
		t.Errorf("a brace-led message that is no notification reads as written: %q", got)
	}
}
